### ISSUE TITLE
It says startWithNext is deprecated

### ISSUE THREAD

**Issue by O-mkar** [AckeeCZ/ReactiveLocation#3]
'startWithNext' is deprecated: This SignalProducer may emit errors which must be handled explicitly, or observed using startWithResult:

**Comment by pteasima** [comment]
This is a recent change in ReactiveCocoa. They want to force you to handle all errors, so you should only do startWithNext on a signal where Error == NoError. In ReactiveSwift (i.e. the swift3.0 version of ReactiveCocoa), this is enforced at compile time. We will be migrating this repo to swift3.0 soon. In the meantime, you have two options:
1) use the deprecated startWithNext method (no harm done here, its deprecated just because there are new best practices).
2) Use the startWithResult method as suggested. This method gives you a https://github.com/antitypical/Result. You can switch on the Result to extract the value or error.
